version: '3.8'

services:
  app:
    build: .
    container_name: bootcamp-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: bootcamp
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/getirbootcamp
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_FORMAT_SQL: "true"
      SPRING_JPA_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_OPEN_IN_VIEW: "true"
      LOGGING_SQL_LEVEL: DEBUG
      LOGGING_BINDER_LEVEL: TRACE
      TOKEN_SECRET_KEY: RaGp4Nfnv1kPukJKmOOG3attmH1Uy6tIpgZ4lRTpNUoGWvBkRbxUD8tJd3EbtBaX
      TOKEN_ACCESS_MAX_AGE: 3600000
      TOKEN_REFRESH_MAX_AGE: 604800000
      TOKEN_REFRESH_COOKIE_NAME: refresh-token

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: getirbootcamp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
