spring:
  application:
    name: ${SPRING_APPLICATION_NAME:bootcamp}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/getirbootcamp}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:true}
        dialect: ${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
      open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:true}

logging:
  level:
    org:
      hibernate:
        SQL: ${LOGGING_SQL_LEVEL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOGGING_BINDER_LEVEL:TRACE}

token:
  secret-key: ${TOKEN_SECRET_KEY:RaGp4Nfnv1kPukJKmOOG3attmH1Uy6tIpgZ4lRTpNUoGWvBkRbxUD8tJd3EbtBaX}
  access-token:
    max-age: ${TOKEN_ACCESS_MAX_AGE:3600000}
  refresh-token:
    max-age: ${TOKEN_REFRESH_MAX_AGE:604800000}
    cookie-name: ${TOKEN_REFRESH_COOKIE_NAME:refresh-token}
