spring:
  application:
    name: bootcamp
  datasource:
    url: jdbc:postgresql://localhost:5432/getirbootcamp
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

token:
  secret-key: RaGp4Nfnv1kPukJKmOOG3attmH1Uy6tIpgZ4lRTpNUoGWvBkRbxUD8tJd3EbtBaX
  access-token:
    max-age: 3_600_000
  refresh-token:
    max-age: 604_800_000
    cookie-name: refresh-token
